iterate all charts and check them for dependencies

diff --git a/.github/workflows/helm-chart-releaser.yml b/.github/workflows/helm-chart-releaser.yml
--- a/.github/workflows/helm-chart-releaser.yml
+++ b/.github/workflows/helm-chart-releaser.yml
@@ -26,17 +26,15 @@ jobs:
       - name: Extract and add dependencies
         run: |
           # Extract dependencies, filter for unique and starting with https
-          repos=()
-          for file in $(find automation -name "Chart.yaml"); do
-              # Perform your desired operation on $file
-              echo "Processing $file"
-              repos+=$(yq eval '.dependencies[].repository' "$file" | grep '^https')
-          done
+          repos=$(find automation -name "Chart.yaml" -exec yq '.dependencies[].repository' {} \; | \
+                  sort | \
+                  uniq | \
+                  grep '^https')
 
           # Loop through repositories and add them
-          for repo in "${repos[@]}"; do
-              echo "Adding repo \"$(basename "$repo")\" with source \"$repo\""
-              helm repo add "$(basename "$repo")" "$repo" || echo "Failed to add \"$repo\""
+          for repo in $repos; do
+            echo "Adding repo \"$(basename "$repo")\" with source \"$repo\""
+            helm repo add "$(basename "$repo")" "$repo" || echo "Failed to add \"$repo\""
           done
 
       # - name: Add Helm dependencies
