test gha

diff --git a/.github/workflows/helm-chart-releaser.yml b/.github/workflows/helm-chart-releaser.yml
--- a/.github/workflows/helm-chart-releaser.yml
+++ b/.github/workflows/helm-chart-releaser.yml
@@ -2,8 +2,8 @@ name: Release Charts
 on:
   workflow_dispatch:
   push:
-    branches:
-      - main
+    # branches:
+    #   - main
 
 concurrency: 
   group: release-helm-chart
@@ -18,42 +18,40 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  #v4.1.1
-        with:
-          fetch-depth: 0
 
-      - name: Configure Git
-        run: |
-          git config user.name "$GITHUB_ACTOR"
-          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
+      # - name: Configure Git
+      #   run: |
+      #     git config user.name "$GITHUB_ACTOR"
+      #     git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
 
-      - name: Extract and add dependencies
-        run: |
-          # Extract dependencies, filter for unique and starting with https
-          repos=$(find automation -name "Chart.yaml" -exec yq '.dependencies[].repository' {} \; | \
-                  sort | \
-                  uniq | \
-                  grep '^https')
+      # - name: Extract and add dependencies
+      #   run: |
+      #     # Extract dependencies, filter for unique and starting with https
+      #     repos=$(find automation -name "Chart.yaml" -exec yq '.dependencies[].repository' {} \; | \
+      #             sort | \
+      #             uniq | \
+      #             grep '^https')
 
-          # Loop through repositories and add them
-          for repo in $repos; do
-            echo "Adding repo \"$(basename "$repo")\" with source \"$repo\""
-            helm repo add "$(basename "$repo")" "$repo" || echo "Failed to add \"$repo\""
-          done
+      #     # Loop through repositories and add them
+      #     for repo in $repos; do
+      #       echo "Adding repo \"$(basename "$repo")\" with source \"$repo\""
+      #       helm repo add "$(basename "$repo")" "$repo" || echo "Failed to add \"$repo\""
+      #     done
 
-      - name: Run chart-releaser
-        uses: helm/chart-releaser-action@a917fd15b20e8b64b94d9158ad54cd6345335584   #v1.6.0
-        with:
-          charts_dir: automation
-        env:
-          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
+      # - name: Run chart-releaser
+      #   uses: helm/chart-releaser-action@a917fd15b20e8b64b94d9158ad54cd6345335584   #v1.6.0
+      #   with:
+      #     charts_dir: automation
+      #   env:
+      #     CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
 
-      - uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
-        if: failure()
-        with:
-          type: ${{ job.status }} 
-          job_name: 'Helmchart Release Status: '
-          url: ${{ secrets.RC_WEBHOOK }}
-          channel: '#dbp-dev-monitoring'
-          username: Helmchart Failure Notificator
+      # - uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
+      #   if: failure()
+      #   with:
+      #     type: ${{ job.status }} 
+      #     job_name: 'Helmchart Release Status: '
+      #     url: ${{ secrets.RC_WEBHOOK }}
+      #     channel: '#dbp-dev-monitoring'
+      #     username: Helmchart Failure Notificator
         
       
