Ops 6833 dependencies not possible in helm chart releaser (#10)
* get dependencies from Chart.yaml
* add log line for dependencies and test action
* iterate all charts and check them for dependencies
* disable debugging changes
* remove hardcoded dependencies

diff --git a/.github/workflows/helm-chart-releaser.yml b/.github/workflows/helm-chart-releaser.yml
--- a/.github/workflows/helm-chart-releaser.yml
+++ b/.github/workflows/helm-chart-releaser.yml
@@ -21,12 +21,20 @@ jobs:
         run: |
           git config user.name "$GITHUB_ACTOR"
           git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
-          
 
-      - name: Add Helm dependencies
+      - name: Extract and add dependencies
         run: |
-          helm repo add bitnami https://charts.bitnami.com/bitnami
-          helm repo add sql_exporter https://burningalchemist.github.io/sql_exporter/
+          # Extract dependencies, filter for unique and starting with https
+          repos=$(find automation -name "Chart.yaml" -exec yq '.dependencies[].repository' {} \; | \
+                  sort | \
+                  uniq | \
+                  grep '^https')
+
+          # Loop through repositories and add them
+          for repo in $repos; do
+            echo "Adding repo \"$(basename "$repo")\" with source \"$repo\""
+            helm repo add "$(basename "$repo")" "$repo" || echo "Failed to add \"$repo\""
+          done
 
       - name: Run chart-releaser
         uses: helm/chart-releaser-action@a917fd15b20e8b64b94d9158ad54cd6345335584   #v1.6.0
